services:
  netbird:
    image: netbirdio/netbird:latest
    container_name: netbird
    cap_add:
      - NET_ADMIN
    environment:
      - NB_SETUP_KEY=${SETUP_KEY}
    volumes:
      - netbird-client:/etc/netbird
    restart: unless-stopped
    networks:
      - netbird

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - netbird
    networks:
      - netbird
    ports:
      - "3000:8080"

volumes:
  netbird-client:
  open-webui:

networks:
  netbird:
    driver: bridge
